[[main]]
  identifier = "about"
  name = "About"
  url = "about"
  weight = 2

[[main]]
  identifier = "archive"
  name = "Archive"
  url = "archive"
  weight = 3

[[main]]
  identifier = "posts"
  name = "Posts"
  url = "post"
  weight = 1
